/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anka_myapp_internal_JNICreateRandomSubGraph */

#ifndef _Included_anka_myapp_internal_JNICreateRandomSubGraph
#define _Included_anka_myapp_internal_JNICreateRandomSubGraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anka_myapp_internal_JNICreateRandomSubGraph
 * Method:    getSubGraphNodes
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_anka_myapp_internal_JNICreateRandomSubGraph_getSubGraphNodes
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
